cc_library(
        name = "isaac_rooms",
        srcs = ["BasementHardRoom.cpp",
                "BasementNormalRoom.cpp",
                "CavesHardRoom.cpp",
                "CavesNormalRoom.cpp",
                "HardRoom.cpp",
                "NormalRoom.cpp",
                "Room.cpp"
        ],
        hdrs = ["BasementHardRoom.h",
                "BasementNormalRoom.h",
                "CavesHardRoom.h",
                "CavesNormalRoom.h",
                "HardRoom.h",
                "NormalRoom.h",
                "Room.h"
        ],
        visibility = ["//visibility:public"],
)
