prefix = "//AbstractFactory/cpp-source/"
cc_binary(
        name = "abstract_factory",
        srcs = [
                "main.cpp"
        ],
        deps = [
                prefix + "rooms:isaac_rooms",
                prefix + "serializers:serializers",
                prefix + "factories:isaac_factories"
        ]
)
