cc_binary(
    name = "adapter",
    srcs = [
            "main.cpp",
            "TextStorage.cpp",
            "JsonStorage.cpp",
            "TextJsonAdapter.cpp",
            "JsonStorage.h",
            "TextJsonAdapter.h",
            "TextStorage.h",
    ],
    deps = ["@boost//:algorithm"]
)
