cc_binary(
    name = "bridge",
    srcs = [
            "main.cpp",
            "axles/Axle.cpp",
            "axles/CarAxle.cpp",
            "axles/PlaneAxle.cpp",
            "include/Axle.h",
            "include/CarAxle.h",
            "include/PlaneAxle.h",
            "wheels/Gamepad.cpp",
            "wheels/PlaneWheel.cpp",
            "wheels/SteeringWheel.cpp",
            "include/Gamepad.h",
            "include/PlaneWheel.h",
            "include/SteeringWheel.h",
    ],
    copts = ["-IBridge/cpp-source/include"],
)

